### ISSUE TITLE
plot(birds) doesn't work

### ISSUE THREAD

**Issue by xrobin** [fcharte/mldr#11]
I get the following error message:

    > library(mldr)
    Enter mldrGUI() to launch mldr's web-based GUI
    > plot(birds)
    Error in if (nrow(value) == length(rn) && ncol(value) == length(cn)) { : 
        missing value where TRUE/FALSE needed

I get the same message when I try to plot various datasets...

Version: I just installed mldr from github, R 3.2.0 from the CRAN ubuntu repository on Ubuntu vivid (15.04).

**Comment by fdavidcl** [comment]
Thank you for the heads-up. This looks like a problem with all "Label Concurrence" plots. Maybe some new change in the `circlize` package (but I'm having trouble downgrading to an earlier version right now). We will look into it and fix it as soon as possible.

**Comment by fdavidcl** [comment]
It's working as expected now. For example:

    > plot(birds, labelIndices = birds$labels$index[1:8])

![birdslc](https://cloud.githubusercontent.com/assets/909629/8269773/3ec33cc8-17b9-11e5-9207-5f8c4b6f67fa.png)
