### ISSUE TITLE
Bugfix report (and possible solution)

### ISSUE THREAD

**Issue by rivolli** [fcharte/mldr#14]
Hello, I use this package and for some sparce datasets I had an error on call the mldr function.
For example: Yahoo datasets http://sourceforge.net/projects/mulan/files/datasets/yahoo.rar

I debug this error and I report this and I propose a simple solution.
The function parse_sparse_data split the data using:
unlist(strsplit(item, " "))

However in some datasets there are a space after the comma, and the result of this code is little different as expected, then my suggest of solution is use a trim, like this:
unlist(strsplit(gsub("^\\s+|\\s+$", "", item), " "))

In my test this work well.
Thanks

**Comment by fdavidcl** [comment]
Thank you for bringing this to our attention. The solution you provided is indeed working fine.

If you need this functionality immediately, please use `devtools::install_github("fcharte/mldr")` to install this new version. We will try to get it up on CRAN as soon as possible.

Thanks again!
