### ISSUE TITLE
NA values instead of zeroes in sparse ARFF files

### ISSUE THREAD

**Issue by alessanderbotti** [fcharte/mldr#21]
It seems to me that, when reading sparse ARFF files (like the ones in the [yahoo dataset](http://sourceforge.net/projects/mulan/files/datasets/yahoo.rar)), mldr is interpreting omitted values as NA values instead of zeros, what differs from the [ARFF format description](http://weka.wikispaces.com/ARFF+%28book+version%29):

> "Note that the omitted values in a sparse instance are 0, they are not "missing" values! If a value is unknown, you must explicitly represent it with a question mark (?)."

Due to this behaviour of the mldr parser, I am having to [manually replace NA values with zeroes](http://stackoverflow.com/questions/8161836/how-do-i-replace-na-values-with-zeros-in-r), and then [rebuild the datasets](https://github.com/fcharte/mldr/blob/master/demo/rebuild_datasets.R).

Thank you very much for the great work in mldr!

**Comment by fcharte** [comment]
You are right Alessander. We will look into it as soon as possible to fix this bug. 

Thank you for using mldr!
