### ISSUE TITLE
bug in write_arff for dataset birds

### ISSUE THREAD

**Issue by rivolli** [fcharte/mldr#30]
I didn't know why, but if I save and try to load the birds dataset it is not work, 
like this:

```
library(mldr)
data("birds")
write_arff(birds, "birds-test", T)
test <- mldr("birds-test")
```

Error in matrix(unlist(value, recursive = FALSE, use.names = FALSE), nrow = nr,  : 
  'data' must be of a vector type, was 'NULL'
In addition: Warning messages:
1: In matrix(unlist(strsplit(arff_data, ",", fixed = T)), ncol = num_attrs,  :
  data length [179955] is not a sub-multiple or multiple of the number of rows [693]
2: In max(msr$count) : no non-missing arguments to max; returning -Inf

I'm using the mldr_0.3.22
Thanks.

**Comment by fdavidcl** [comment]
Hi @rivolli, thanks for the heads-up.

The `write_arff` function is not correctly enclosing attribute names withing quotes nor is it escaping single quotes, as can be seen in the picture (original on the left, mldr-generated on the right):

![captura de pantalla de 2016-07-26 18-12-22](https://cloud.githubusercontent.com/assets/909629/17150484/f2c7061c-536f-11e6-9fb5-c877b5a61c04.png)

A fix is being worked on. I'm having a hard time escaping quotes on R but I hope I'll work it out :grin:.

**Comment by fdavidcl** [comment]
dea502a fixes the behavior @rivolli described. Now writing the *birds* dataset generates a correct ARFF file. I want to further test this with other datasets to be sure it works in general.

**Comment by 980432776** [comment]
Hi, I get a question to consult you. In RStudio, I preprocessed the Yeast dataset by REMEDIAL, and then use R function _write.arff_ to get the preprocessed dataset with format _arff_. Finally I put it into meka/weka, but it can't open in meka/weka. So I can't use multilabel classifiers to classify it. Can you help me to deal with this problem? Thanks! The following are my R codes :
decoupled.yeast<-dilMean(yeast)
summary(decoupled.yeast)
decoupled.yeast1<-dilThirdQ(yeast)
summary(decoupled.yeast1)
decoupled.yeast_m<-as.data.frame.AsIs(decoupled.yeast) #coerce it to be a data frame
#将预处理后的数据导出到meka数据集，#要添加foreign包
write.arff(decoupled.yeast_m,file ="C:/Users/Administrator/Desktop/WEKA/meka 数据集/decoupled_yeast.arff")
